server:
  port: 8001

mybatis:
  mapperLocations: classpath:mybatis/*-mapper.xml
  config: classpath:mybatis/mybatis-conf.xml
  typeAliasesPackage: com.mop
  checkConfigLocation: false

#Product
spring:
  datasource:
    url: jdbc:mysql://172.31.65.110:3306/app_test_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: xm_test_data_dev
    password: cNaNCW4vEruhXrK8OXBSWmmCc
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    test-while-borrow: true
    validation-query: SELECT 1 FROM log_center_test_testresult
    time-between-evication-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 30MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    async:
      request-timeout: 3600000

#Test
#spring:
#  datasource:
#    url: jdbc:mysql://172.31.65.153:3306/base_center?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: data_center_dev
#    password: vJ&pvVIdCdgQeFEK%4wk
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    test-while-idle: true
#    test-while-borrow: true
#    validation-query: SELECT 1 FROM log_center_test_testresult
#    time-between-evication-runs-millis: 300000
#    min-evictable-idle-time-millis: 1800000
#  sevelet:
#    multipart:
#      maxFileSize: 1024MB
#      maxRequestSize: 1024MB
#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#  mvc:
#    async:
#      request-timeout: 3600000